### ISSUE TITLE
Syntax Error when executing command

### ISSUE THREAD

**Issue by mfix22** [bartveneman/wallace-cli#69]
Very cool tool! No rush to fix this _ever_, only creating this issue in case you wanted to. 

Try: `wallace https://carbon.now.sh`

**Comment by bartveneman** [comment]
Thanks for reporting! It seems that there is a CSS Syntax Error in your CSS, causing the analyzer to break:

```css
.container.jsx-1841802010 {
	position: relative;
	undefined;
}
```

The error reporting could be clearer though. Leaving this issue open to allocate some time for that. Error is reported by @projectwalace/css-analyzer and only displayed here.
